### PR TITLE
Feature/hu2002 create product list

### PR DESCRIPTION
**Pull request by Katkat04**
my work is ready, I hope you liked what I did.

### CODE REVIEW

**Comment by Katkat04** [comment]
PC view 
image
image
image

Mobile view 
image
image

Little mobile view 
image
image

**Review by RDCelin — APPROVED** [review]
Great design

**Review by Edimar-star — APPROVED** [review]
Good design and excellent work, I liked the proportion of the elements.

**Review by caleones — APPROVED** [review]

**Review by jesusdlacrz — APPROVED** [review]
excellent, fits perfectly with the home page and looks great responsive design

**Pull request merged**
